#template_path: "noop.j2"
template:
  url: https://raw.githubusercontent.com/zaro0508/organizations-infra/mytest1/sceptre/itsandbox/templates/noop.j2
  type: http
stack_name: "b"
dependencies:
  - http/a.yaml
sceptre_user_data:
  MyName: "ben"
