#template_path: "noop.j2"
template:
  url: https://raw.githubusercontent.com/zaro0508/organizations-infra/mytest1/sceptre/itsandbox/templates/noop.py
  type: http
stack_name: "c"
stack_tags:
  team: lakers
  sport: bball
sceptre_user_data:
  MyName: "calvin"
